DROP PROCEDURE IF EXISTS InsertDummyUsersAndProfiles;
DROP PROCEDURE IF EXISTS InsertDummyCompaniesAndJobs;
DROP PROCEDURE IF EXISTS InsertDummySkills;
DROP PROCEDURE IF EXISTS ApplyForJob;
DROP PROCEDURE IF EXISTS ConnectUsers;
DROP PROCEDURE IF EXISTS CreatePost;
DROP PROCEDURE IF EXISTS GetUserFullProfile;
DROP PROCEDURE IF EXISTS InsertDummyEducation;
DROP PROCEDURE IF EXISTS INsertDummyUserSkills;
SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE user;
TRUNCATE TABLE profile;
TRUNCATE TABLE connection;
TRUNCATE TABLE post;
TRUNCATE TABLE reaction;
TRUNCATE TABLE message;
TRUNCATE TABLE company;
TRUNCATE TABLE job;
TRUNCATE TABLE job_application;
TRUNCATE TABLE skill;
TRUNCATE TABLE education;
TRUNCATE TABLE user_skill;

SET FOREIGN_KEY_CHECKS = 1;